name: Merge M3U Files

on:
  push:
    paths:
      - 'CNTV-V4.m3u'
      - 'douyuyqk.m3u'
      - 'huyayqk.m3u'
      - 'yylunbo.m3u'
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0/5 * * *'  # 每天UTC时间0点运行

jobs:
  merge-m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Clean up old IPTV.m3u
      run: |
        # 删除旧的IPTV.m3u文件（如果存在）
        if [ -f "IPTV.m3u" ]; then
          echo "删除旧的IPTV.m3u文件..."
          rm -f IPTV.m3u
          echo "旧文件已删除"
        else
          echo "没有找到旧的IPTV.m3u文件"
        fi
        
    - name: Merge M3U files with EPG
      run: |
        # 创建新的m3u文件头，包含EPG信息
        echo "#EXTM3U x-tvg-url=\"https://epg.112114.xyz/pp.xml\"" > IPTV.m3u
        echo "" >> IPTV.m3u
        
        # 按顺序合并各个文件（跳过每个文件的头部）
        for file in CNTV-V4.m3u douyuyqk.m3u huyayqk.m3u yylunbo.m3u; do
          if [ -f "$file" ]; then
            echo "正在合并 $file..."
            # 跳过第一行（EXTM3U头）并追加内容
            tail -n +2 "$file" >> IPTV.m3u
            # 添加空行分隔不同的文件内容
            echo "" >> IPTV.m3u
          else
            echo "警告: $file 不存在"
          fi
        done
        
        echo "合并完成！新文件已创建"
        
    - name: Validate and show file info
      run: |
        echo "=== 文件验证 ==="
        if [ ! -f "IPTV.m3u" ]; then
          echo "错误: IPTV.m3u 文件未创建成功"
          exit 1
        fi
        
        echo "=== 文件统计信息 ==="
        echo "IPTV.m3u 行数: $(wc -l < IPTV.m3u)"
        echo "文件大小: $(ls -lh IPTV.m3u | awk '{print $5}')"
        echo ""
        echo "文件前5行内容:"
        head -5 IPTV.m3u
        echo ""
        echo "文件最后3行内容:"
        tail -3 IPTV.m3u
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 添加生成的文件
        git add IPTV.m3u
        
        # 检查是否有更改需要提交
        if git diff --staged --quiet; then
          echo "没有变化需要提交"
        else
          git commit -m "自动更新: 合并直播源文件并添加EPG支持 [$(date +'%Y-%m-%d %H:%M')]"
          git push
        fi
