name: Update

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron: 0 */5 * * *
  
env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3

    - name: GetTime
      id: date
      run: |
        current_date=$(date +'%Y-%m-%d %H:%M:%S')
        echo "date=$current_date" >> $GITHUB_OUTPUT

    - name: Update
      run: |
        # 国内IPV6-TV源
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O IPTV-V6.m3u
       
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CCTV-V6.m3u && sed -i -n '/央视频道/,+1p'  CCTV-V6.m3u 
        sed -i '1i #EXTM3U' CCTV-V6.m3u
        sed -i '/^\s*$/d' CCTV-V6.m3u

        rm -f CNTV-V6.m3u && touch CNTV-V6.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV1.m3u && sed -i -n '/卫视频道/,+1p' CNTV1.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV2.m3u && sed -i -n '/NewTV系列/,+1p' CNTV2.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV3.m3u && sed -i -n '/超清频道/,+1p' CNTV3.m3u

        cat CCTV-V6.m3u >> CNTV-V6.m3u
        cat CNTV1.m3u >> CNTV-V6.m3u
        cat CNTV2.m3u >> CNTV-V6.m3u
        cat CNTV3.m3u >> CNTV-V6.m3u
        rm -f CNTV1.m3u CNTV2.m3u CNTV3.m3u
        sed -i '/#EXTM3U/d' CNTV-V6.m3u
        sed -i '1i #EXTM3U' CNTV-V6.m3u
        sed -i '/^\s*$/d' CNTV-V6.m3u

        # 国内IPV4-TV源
        wget "https://live.ottiptv.cc/iptv.m3u?userid=8137863657&sign=2c8d82c9f17f480726d4770be9d0fb33fd0fcb31e1024448c36663605ea6a3f99e5bd467b68c287e3f0c07f85b95a188139aa3f19e227e251dc707bce0ededaab73ceeaddf6195&auth_token=54741b289e946919fc1c34ca88db58a4" -O IPTV-V4.m3u
        
        rm -f CCTV-V4.m3u && touch CCTV-V4.m3u
        cat IPTV-V4.m3u  >> CCTV-V4.m3u && sed -i -n '/央视/,+1p'  CCTV-V4.m3u 
        sed -i '1i #EXTM3U x-tvg-url="https://11.112114.xyz/pp.xml"' CCTV-V4.m3u
        sed -i '/^\s*$/d' CCTV-V4.m3u

        rm -f CNTV-V4.m3u && touch CNTV-V4.m3u
        cat IPTV-V4.m3u  >> CNTV1.m3u && sed -i -n '/卫视/,+1p' CNTV1.m3u
        cat IPTV-V4.m3u  >> CNTV2.m3u && sed -i -n '/地方/,+1p' CNTV2.m3u
        cat IPTV-V4.m3u  >> CNTV3.m3u && sed -i -n '/影视/,+1p' CNTV3.m3u
        cat IPTV-V4.m3u  >> CNTV4.m3u && sed -i -n '/其他/,+1p' CNTV4.m3u
        cat IPTV-V4.m3u  >> CNTV5.m3u && sed -i -n '/体育/,+1p' CNTV5.m3u

        cat CCTV-V4.m3u >> CNTV-V4.m3u
        cat CNTV1.m3u >> CNTV-V4.m3u
        cat CNTV2.m3u >> CNTV-V4.m3u
        cat CNTV3.m3u >> CNTV-V4.m3u
        cat CNTV4.m3u >> CNTV-V4.m3u
        cat CNTV5.m3u >> CNTV-V4.m3u
        rm -f CNTV1.m3u CNTV2.m3u CNTV3.m3u CNTV4.m3u CNTV5.m3u
        sed -i '/#EXTM3U/d' CNTV-V4.m3u
        sed -i '1i #EXTM3U x-tvg-url="https://11.112114.xyz/pp.xml"' CNTV-V4.m3u
        sed -i '/^\s*$/d' CNTV-V4.m3u

        # 直播源
        rm -f Live.m3u && wget https://bit.ly/IPTV-Gather -O Live.m3u
        sed -i '/#EXTM3U/d' Live.m3u
        sed -i '1i #EXTM3U' Live.m3u
        sed -i '/^\s*$/d' Live.m3u

        # 虎牙一起看
        rm -f huyayqk.m3u && wget https://sub.ottiptv.cc/huyayqk.m3u -O huyayqk.m3u
        sed -i '/#EXTM3U/d' huyayqk.m3u
        sed -i '1i #EXTM3U' huyayqk.m3u
        sed -i '/^\s*$/d' huyayqk.m3u

        # 斗鱼一起看
        rm -f douyuyqk.m3u && wget https://sub.ottiptv.cc/douyuyqk.m3u -O douyuyqk.m3u
        sed -i '/#EXTM3U/d' douyuyqk.m3u
        sed -i '1i #EXTM3U' douyuyqk.m3u
        sed -i '/^\s*$/d' douyuyqk.m3u

        # bilibili直播
        rm -f bililive.m3u && wget https://sub.ottiptv.cc/bililive.m3u -O bililive.m3u
        sed -i '/#EXTM3U/d' bililive.m3u
        sed -i '1i #EXTM3U' bililive.m3u
        sed -i '/^\s*$/d' bililive.m3u

        # YY轮播
        rm -f yylunbo.m3u && wget https://sub.ottiptv.cc/yylunbo.m3u -O yylunbo.m3u
        sed -i '/#EXTM3U/d' yylunbo.m3u
        sed -i '1i #EXTM3U' yylunbo.m3u
        sed -i '/^\s*$/d' yylunbo.m3u
        
        # 节目源
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        echo "Auto Update in ${{ steps.date.outputs.date }}
        ## 注意！使用V4源时需配置代理，可仿照APTV进行配置

        电视节目源订阅地址（TV源）：

        节目单订阅地址：https://peterhchina.github.io/iptv/EPG.xml
        
        IPV6-TV源

        央视频道源：https://peterhchina.github.io/iptv/CCTV-V6.m3u  

        央视+卫视+地方+影视源：https://peterhchina.github.io/iptv/CNTV-V6.m3u  

        全部V6-TV源：https://peterhchina.github.io/iptv/IPTV-V6.m3u

        IPV4-TV源

        央视频道源：https://peterhchina.github.io/iptv/CCTV-V4.m3u  

        央视+卫视+地方+影视源：https://peterhchina.github.io/iptv/CNTV-V4.m3u  

        全部V4-TV源：https://peterhchina.github.io/iptv/IPTV-V4.m3u

        网络直播订阅地址：
        
        斗鱼一起看：https://peterhchina.github.io/iptv/huyayqk.m3u  

        虎牙一起看：https://peterhchina.github.io/iptv/douyuyqk.m3u  

        bilibili直播：https://peterhchina.github.io/iptv/bililive.m3u  

        YY轮播：https://peterhchina.github.io/iptv/yylunbo.m3u  

        其他直播源大合集：https://peterhchina.github.io/iptv/Live.m3u  

        *自定义header：User-Agent=okHttp/Mursor-1.4.0.0
        
        ![image](https://github.com/peterHchina/iptv/blob/main/src/VC20250811-092617.png)
        ![image](https://github.com/peterHchina/iptv/blob/main/src/VC20250811-100707.jpg)

        ## Star History
        <a href='https://star-history.com/#peterHchina/iptv&Date'>
        <picture>
        <source media='(prefers-color-scheme: dark)' srcset='https://api.star-history.com/svg?repos=peterHchina/iptv&type=Date&theme=dark' />
        <source media='(prefers-color-scheme: light)' srcset='https://api.star-history.com/svg?repos=peterHchina/iptv&type=Date' />
        <img alt='Star History Chart' src='https://api.star-history.com/svg?repos=peterHchina/iptv&type=Date' />
        </picture>
        </a>" > README.md

    - name: Clean
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "${{ steps.date.outputs.date }}"
        git branch -D main
        git branch -m main
        
    - name: Push
      run: git push -f origin main
